[project]
name = "starlink-monitor"
version = "0.1.0"
description = "Simple Starlink monitoring tool"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django-cors-headers>=4.9.0",
    "django-ninja>=1.5.3",
    "django-timescaledb>=0.2.13",
    "environs>=14.6.0",
    "h3>=4.4.2",
    "loguru>=0.7.3",
    "psycopg[binary,extras,pool]>=3.3.3",
    "requests>=2.32.5",
]
