{
 "title": "Netera",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "starlink",
     "rawSql": "SELECT\n  ts AS \"time\",\n  ping_latency_ms_avg AS \"Latency (ms)\",\n  (ping_drop_rate_avg * 100.0) AS \"Drop Rate (%)\"\nFROM telemetry_u\nWHERE $__timeFilter(ts)\nORDER BY ts;"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "starlink",
     "rawSql": "SELECT\n  ts AS \"time\",\n  uplink_throughput_mbps AS \"Upload (Mbps)\"\nFROM telemetry_u\nWHERE $__timeFilter(ts)\nORDER BY ts;"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "starlink",
     "rawSql": "SELECT\n  ts AS \"time\",\n  downlink_throughput_mbps AS \"Download (Mbps)\"\nFROM telemetry_u\nWHERE $__timeFilter(ts)\nORDER BY ts;"
    }
   ]
  }
 ]
}