# Generated by Django 6.0.2 on 2026-03-01 16:06

import django.contrib.postgres.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('device_id', models.TextField(db_index=True)),
                ('device_type', models.TextField(default='i')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('ipv6_ue', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('ipv6_cpe', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('utc_timestamp_ns', models.BigIntegerField()),
            ],
            options={
                'db_table': 'telemetry_i',
                'indexes': [models.Index(fields=['device_id', '-ts'], name='telemetry_i_dev_ts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('device_type__in', ['u', 'r', 'i'])), name='telemetry_i_device_type_allowed')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('device_id', models.TextField(db_index=True)),
                ('device_type', models.TextField(default='r')),
                ('wifi_uptime_s', models.IntegerField(blank=True, null=True)),
                ('wifi_software_version', models.TextField(blank=True, null=True)),
                ('wifi_hardware_version', models.TextField(blank=True, null=True)),
                ('wifi_is_repeater', models.BooleanField(blank=True, null=True)),
                ('wifi_hops_from_controller', models.IntegerField(blank=True, null=True)),
                ('wifi_is_bypassed', models.BooleanField(blank=True, null=True)),
                ('internet_ping_drop_rate', models.FloatField(blank=True, null=True)),
                ('internet_ping_latency_ms', models.FloatField(blank=True, null=True)),
                ('wifi_pop_ping_drop_rate', models.FloatField(blank=True, null=True)),
                ('wifi_pop_ping_latency_ms', models.FloatField(blank=True, null=True)),
                ('dish_ping_drop_rate', models.FloatField(blank=True, null=True)),
                ('dish_ping_latency_ms', models.FloatField(blank=True, null=True)),
                ('clients', models.IntegerField(blank=True, null=True)),
                ('clients_2ghz', models.IntegerField(blank=True, null=True)),
                ('clients_5ghz', models.IntegerField(blank=True, null=True)),
                ('clients_eth', models.IntegerField(blank=True, null=True)),
                ('wan_rx_bytes', models.BigIntegerField(blank=True, null=True)),
                ('wan_tx_bytes', models.BigIntegerField(blank=True, null=True)),
                ('clients_2ghz_rx_rate_mbps_min', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_rx_rate_mbps_max', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_rx_rate_mbps_avg', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_rx_rate_mbps_min', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_rx_rate_mbps_max', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_rx_rate_mbps_avg', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_tx_rate_mbps_min', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_tx_rate_mbps_max', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_tx_rate_mbps_avg', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_tx_rate_mbps_min', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_tx_rate_mbps_max', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_tx_rate_mbps_avg', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_signal_strength_min', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_signal_strength_max', models.FloatField(blank=True, null=True)),
                ('clients_2ghz_signal_strength_avg', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_signal_strength_min', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_signal_strength_max', models.FloatField(blank=True, null=True)),
                ('clients_5ghz_signal_strength_avg', models.FloatField(blank=True, null=True)),
                ('dish_id', models.TextField(blank=True, null=True)),
                ('api_version', models.TextField(blank=True, null=True)),
                ('active_alerts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True)),
                ('utc_timestamp_ns', models.BigIntegerField()),
            ],
            options={
                'db_table': 'telemetry_r',
                'indexes': [models.Index(fields=['device_id', '-ts'], name='telemetry_r_dev_ts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('device_type__in', ['u', 'r', 'i'])), name='telemetry_r_device_type_allowed')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('device_id', models.TextField(db_index=True)),
                ('device_type', models.TextField(default='u')),
                ('downlink_throughput_mbps', models.FloatField(blank=True, null=True)),
                ('uplink_throughput_mbps', models.FloatField(blank=True, null=True)),
                ('ping_drop_rate_avg', models.FloatField(blank=True, null=True)),
                ('ping_latency_ms_avg', models.FloatField(blank=True, null=True)),
                ('obstruction_percent_time', models.FloatField(blank=True, null=True)),
                ('uptime_s', models.IntegerField(blank=True, null=True)),
                ('signal_quality', models.FloatField(blank=True, null=True)),
                ('h3_cell_id', models.BigIntegerField(blank=True, null=True)),
                ('seconds_until_swupdate_reboot_possible', models.IntegerField(blank=True, null=True)),
                ('running_software_version', models.TextField(blank=True, null=True)),
                ('active_alerts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True)),
                ('utc_timestamp_ns', models.BigIntegerField()),
                ('ut_lat', models.FloatField(blank=True, null=True)),
                ('ut_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry_u',
                'indexes': [models.Index(fields=['device_id', '-ts'], name='telemetry_u_dev_ts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('device_type__in', ['u', 'r', 'i'])), name='telemetry_u_device_type_allowed')],
            },
        ),
    ]
