# Generated by Django 6.0.2 on 2026-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarlinkMetadata',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'starlink_metadata',
            },
        ),
    ]
