# Generated by Django 6.0.2 on 2026-03-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_starlinkmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarlinkDeviceInfo',
            fields=[
                ('device_id', models.TextField(primary_key=True, serialize=False)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('subscription_id', models.TextField(blank=True, null=True)),
                ('user_terminal_kit', models.TextField(blank=True, null=True)),
                ('user_terminal_dish', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'starlink_device_info',
            },
        ),
    ]
