# Generated by Django 6.0.2 on 2026-03-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_starlinkdeviceinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starlinkdeviceinfo',
            old_name='user_terminal_dish',
            new_name='user_terminal_dish_id',
        ),
        migrations.RenameField(
            model_name='starlinkdeviceinfo',
            old_name='user_terminal_kit',
            new_name='user_terminal_kit_id',
        ),
        migrations.AddField(
            model_name='starlinkdeviceinfo',
            name='router_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
